### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by apps4u** [JetBrains/kotlinconf-app#10]
Hi I have a question about the project folder structure, I'm not sure if this is designed or just happened to happen like this. 

So Some project have a package in the src directory, other have src/main/kotlin now I know both are valid and depends on user creating project, But then when I look at the Android project all sources are in a java folder src/main/java. 

So is this because of how the project was put together or is their a valid reason. Im asking this question as I'm trying to get Kotlin in to our company and all 3 developers I got to download this project were confused by the different project folder layouts but that was easy to explain but I don't know why the Android project would have sources under java and could not explain why. 

IF this is not by design I happy to fix and issue a pull request as I think samples like this should be clear and consistent, As confusion among our developer just makes it that much harder to let our managers let us try Kotlin in a production app. The quicker staff feel comfit-able the easer it is to have them learn a new language and have management agree.

**Comment by MarcinMoskala** [comment]
Recommendations for directory structure are described on Coding Conventions section of Kotlin documentation:
https://kotlinlang.org/docs/reference/coding-conventions.html#directory-structure 

As you might have noticed, we already made some cleanup but in the future, we will probably remove folders for base packages (org/jetbrains/kotlinconf). Though we are still discussing this change.
