### ISSUE TITLE
Why `wasmJs` + `js`?

### ISSUE THREAD

**Issue by YektaDev** [JetBrains/kotlinconf-app#145]
Hi!

I was wondering why `wasmJs` isn't used independently for the browser target. This approach could eliminate the need for a common "browser" source set and the additional task of merging the two for building and running the browser app. Is the `js` target really necessary?

**Comment by AndrazP** [comment]
I believe it’s to ensure compatibility with Safari, which doesn’t fully support WASM yet, hence the need for a JS fallback.

**Comment by YektaDev** [comment]
> I believe it’s to ensure compatibility with Safari, which doesn’t fully support WASM yet, hence the need for a JS fallback.

I don't think so.

1. If you meant a fallback that just says "Your browser is not capable of running this app.", that can be defined in `wasmJsMain/resources/index.html`.

2. If you meant an actual fallback application, which I don't think you did, there's no fallback for the application itself because it would need to be an entirely separate UI, possibly on top of Compose HTML, which is entirely different and not present in this codebase. This is the JS entry point, which directly relies on WASM:

```kotlin
package org.jetbrains.kotlinconf

import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.window.CanvasBasedWindow
import org.jetbrains.skiko.wasm.onWasmReady

@OptIn(ExperimentalComposeUiApi::class)
fun main() {
    onWasmReady {
        CanvasBasedWindow {
            App(ApplicationContext())
        }
    }
}
```

**Comment by JSMonk** [comment]
@AndrazP is right. The JS target is only used as a fallback target. 
The code that chose which target to use is placed here:
https://github.com/JetBrains/kotlinconf-app/blob/master/shared/src/webMain/resources/index.html#L197

**Comment by YektaDev** [comment]
Oh, `skiko.js`! So that's how the fallback operates.
Thanks for the clarification!
