### ISSUE TITLE
How to run iOS application with tools?

### ISSUE THREAD

**Issue by liuhea** [JetBrains/kotlinconf-app#2]
How to run iOS application with tools?

**Comment by Dahlgren** [comment]
1. Go into the `ios` directory and open `konan.xcworkspace` with Xcode
2. Select the `konan` project in the explorer view
3. Select the `helperlib` target
4. Set a valid team, your own "Personal Team" will do
5. Select the `konan` target
6. Set a valid team, your own "Personal Team" will do
7. Change the "Bundle Identifier" into something unique
8. Select a x64 iOS device as build target (your phone), the simulator doesn't work currently
9. Build and run on your device
10. If this is the first time deploying to your device with your "Team" it will require you to approve your developer profile. Open the Settings app on your phone and go into General -> Device Management -> Your Profile -> Trust. Then start the kotlin app again.

**Comment by jorgecoca** [comment]
This is very useful if you clone the repository, but what would be the necessary steps to start an iOS app from zero using Kotlin-Native?

**Comment by Dahlgren** [comment]
You could checkout the new Kotlin support in CLion which is available in the EAP version after Kotlin and Kotlin/Native plugins are installed. It adds some example projects including one fullstack app similar to this one. Read more in the recent blog post, https://blog.jetbrains.com/kotlin/2017/11/kotlinnative-ide-support-preview/

**Comment by OlexandrStepanov** [comment]
I have followed the steps from the provided page regarding Kotlin support in CLion IDE.
However, one thing discouraged me: what are the rules of Objective-C syntax translation to the Kotlin? For example, [UIAlertController init method](https://developer.apple.com/documentation/uikit/uialertcontroller/1620092-alertcontrollerwithtitle?language=objc), how to call it from Kotlin?
And how can one achieve autocompletion for native iOS classes in CLion? Without it the development is simply the hell.

**Comment by Querschlag** [comment]
I saw that Kotlin Native uses the "old" Objective-C classes and APIs. With the introduction of Swift the iOS SDK gained a lot of improvements to the APIs like the decision to drop the "NS" for Foundation classes and simplifying function signatures.
Will there be support for exposing the Swift classes to Kotlin Native in the future and is this a thing the team is already working on?

**Comment by hgonzalez94** [comment]
Does this not support building and running against i386 simulator architecture? I seem to only be able to run this on a device.

**Comment by Dahlgren** [comment]
iOS Simulator is supported from Kotlin/Native v0.5, https://blog.jetbrains.com/kotlin/2017/12/kotlinnative-v0-5-released-calling-kotlin-from-swift-and-c-llvm-5-and-more/

**Comment by hgonzalez94** [comment]
I saw that after I posted this (of course). Thanks for the direction fam. Really liking the progress on this. I'll close this for now, but do you know if any of the llvm hooks work with a similar implementation to the late Robovm, or is this all new? 

Intel was put on something similar but i'm pretty sure it died. I know peeps that still rollin with robovm in production so I was just curious.

**Comment by vascoV** [comment]
Hey, great that we can use kotlin native for ios dev.. But currently, I am facing the following issues
<img width="865" alt="screen shot 2018-03-09 at 12 03 22 pm" src="https://user-images.githubusercontent.com/15817701/37202092-3c579a8c-2392-11e8-8396-1ac3b48d018b.png">


Any ideas how to solve it? why it can't determine my java version of 9.0.1?

**Comment by vitaliyistomov** [comment]
@vascoV get Java 8 :)

**Comment by vascoV** [comment]
@vitaliyistomov still getting errors
<img width="863" alt="screen shot 2018-03-09 at 2 47 44 pm" src="https://user-images.githubusercontent.com/15817701/37208159-fe67898c-23a8-11e8-98f4-f99ad80afd62.png">

**Comment by bagza** [comment]
@vascoV 
There is nothing you can do, but to debug your logs. It's build with gradle, so you can run commands in the terminal with log flags provided.

Try to run from the project folder
`./gradlew :compileKonanLibsIphone -- info` to get more symptoms. Also you can get list of available gradle tasks and try them. 

Provide some more information, if you've changed any build files, or versions?

**Comment by thevery** [comment]
Same problem here:
```
> Task :compileKonanAppIphone
Putting task artifact state for task ':compileKonanAppIphone' into context took 0.0 secs.
Executing task ':compileKonanAppIphone' (up-to-date check took 0.001 secs) due to:
  Task has failed previously.
Run tool: konanc with args: -output /Users/thevery/git/kotlinconf-app/ios/build/konan/bin/iphone/app.kexe -repo /Users/thevery/git/kotlinconf-app/ios/build/konan/bin/iphone -repo /Users/thevery/git/kotlinconf-app/ios/build/konan/libs/iphone -library /Users/thevery/git/kotlinconf-app/ios/build/konan/libs/iphone/libs.klib -produce program -linkerOpts -rpath @executable_path/Frameworks -F/Users/thevery/git/kotlinconf-app/ios/Frameworks -F/Users/thevery/Library/Developer/Xcode/DerivedData/konan-eppihodimhqerfbaoucqvuqoqxet/Build/Products/Debug-iphoneos -target iphone /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/AboutViewController.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/SessionViewController.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/AppDelegate.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/SessionsViewController.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/dateUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/coreDataUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/misc.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/networkUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/interopUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/main.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/KonfService.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/KonfLoader.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/FavoritesManager.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/dataUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/NetworkService.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/VotesManager.kt
Starting process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java''. Working directory: /Users/thevery/git/kotlinconf-app/ios Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java -Djava.library.path=/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/nativelib -Dkonan.home=/Users/thevery/.konan/kotlin-native-macos-0.3.4 -Xmx3G -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/kotlin-stdlib.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/klib.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/Runtime.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/protobuf-java-2.6.1.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/shared.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/kotlin-script-runtime.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/kotlin-compiler.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/kotlin-reflect.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/utilities.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/backend.native.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/StubGenerator.jar:/Users/thevery/.konan/kotlin-native-macos-0.3.4/konan/lib/Indexer.jar org.jetbrains.kotlin.cli.utilities.MainKt konanc -output /Users/thevery/git/kotlinconf-app/ios/build/konan/bin/iphone/app.kexe -repo /Users/thevery/git/kotlinconf-app/ios/build/konan/bin/iphone -repo /Users/thevery/git/kotlinconf-app/ios/build/konan/libs/iphone -library /Users/thevery/git/kotlinconf-app/ios/build/konan/libs/iphone/libs.klib -produce program -linkerOpts -rpath @executable_path/Frameworks -F/Users/thevery/git/kotlinconf-app/ios/Frameworks -F/Users/thevery/Library/Developer/Xcode/DerivedData/konan-eppihodimhqerfbaoucqvuqoqxet/Build/Products/Debug-iphoneos -target iphone /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/AboutViewController.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/SessionViewController.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/AppDelegate.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/ui/SessionsViewController.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/dateUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/coreDataUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/misc.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/networkUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/util/interopUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/main.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/KonfService.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/KonfLoader.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/FavoritesManager.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/dataUtils.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/NetworkService.kt /Users/thevery/git/kotlinconf-app/ios/src/main/kotlin/data/VotesManager.kt
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java''
KtFile: FavoritesManager.kt
KtFile: KonfLoader.kt
KtFile: KonfService.kt
KtFile: NetworkService.kt
KtFile: VotesManager.kt
KtFile: dataUtils.kt
KtFile: main.kt
KtFile: AboutViewController.kt
KtFile: AppDelegate.kt
KtFile: SessionViewController.kt
KtFile: SessionsViewController.kt
KtFile: coreDataUtils.kt
KtFile: dateUtils.kt
KtFile: interopUtils.kt
KtFile: misc.kt
KtFile: networkUtils.kt
ld: warning: directory not found for option '-F/Users/thevery/Library/Developer/Xcode/DerivedData/konan-eppihodimhqerfbaoucqvuqoqxet/Build/Products/Debug-iphoneos'
ld: framework not found helperlib
error: linker invocation reported errors

:compileKonanAppIphone (Thread[Task worker for ':',5,main]) completed. Took 31.697 secs.

FAILURE: Build failed with an exception.
```
Xcode 9.3

**Comment by MarcinMoskala** [comment]
Well, architecture changes a lot in the meantime. Now all you need it to open konfios folder as a project in Xcode and play. In case of problems run first:
```
./gradle :common:iosMain:build
```

And then start in Xcode.
