### ISSUE TITLE
Favorites dropped

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/kotlinconf-app#47]
Here's a slack thread quote:
> The Android app doesn't seem to save favorites properly. My whole team lost our favorite lists

> Wow. I just checked, saw my favorites for about half a second, and they all disappeared, and now, they are not coming back... I'll use ink and paper or a notes/calendar app to keep track of the talks I'll attend then...

**Comment by e5l** [comment]
Hi, @LouisCAD .
Sorry for the late response. Unfortunately, we dropped the favorites during yesterday backend fixing. Everything should be ok now.

`copy from slack`
