### ISSUE TITLE
How to execute the tests in common?

### ISSUE THREAD

**Issue by alexkamp** [JetBrains/kotlinconf-app#5]
There is a test in common/src/test. 

Am I right in assuming that this test can be executed against both, the JS implementation of parseDate() and the JVM implementation of it?

If I run `gradle build`, the test shows up in the report in common-jvm/build/reports, so I guess that the JVM implementation passes the test. 

How can I run the test and see the result for the JavaScript implementation?

**Comment by MarcinMoskala** [comment]
With new MPP plugin, all you need it to start `:common:check` task. So:
```
./gradlew :common:check
```
