### ISSUE TITLE
Xcode build error: No such module 'MBProgressHUD'

### ISSUE THREAD

**Issue by jeremyrempel** [JetBrains/kotlinconf-app#61]
1. Git clone repo
2. ./gradlew build (verify success)
3. Open project in XCode, Product -> Build

iOS fails to compile with error: No such module 'MBProgressHUD'

**Comment by lumueller** [comment]
@jeremyrempel Hi, may I ask, what was your fix? I am having the same problem. Thx!

**Comment by queiroz** [comment]
@lumueller Hey, just cd into "konfios" and "pod install". If you don't have it installed then "sudo gem install cocoapods".
