### ISSUE TITLE
API Key in public

### ISSUE THREAD

**Issue by korostenskyi** [JetBrains/kotlinconf-app#75]
https://github.com/JetBrains/kotlinconf-app/blob/d56c3383d52dfdc32ba449d8daf9b9f633dd1d08/iosApp/iosApp/Info.plist#L32

In `build.gradle.kts` we get the Mapbox API key from `local.properties`. Before that, it is required to get our own API key at https://www.mapbox.com/

But here your API key is public. I think it is a mistake. Correct me, if I'm wrong, please.

Thank you!

**Comment by e5l** [comment]
dropped
